language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

php:
  - 5.2
  - 5.3.0
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script: ./vendor/bin/phpunit -c phpunit.xml.dist

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.2
    - php: 5.3.0

notifications:
  email: false